### ISSUE TITLE
Investigate the cost of using various LLMs

### ISSUE THREAD

**Issue by raulfrk** [Vis4Sense/student-projects#6]
Analyse the different approaches to use LLMs for the purpose of the project. Perform cost analysis for some of the models and produce a table with costs for each usage method (e.g Web API, self-hosted....).

**Comment by raulfrk** [comment]
A new document was added as part of [this](https://github.com/Vis4Sense/student-projects/commit/aedeac9d53bc0e4d846db05d66d4bcbd94a7cebd)

**Comment by kaidatavis** [comment]
https://github.com/Vis4Sense/student-projects/blob/main/2023-2024/raul-farkas/resources/llm_cost_research.md
