### ISSUE TITLE
Investigate which market the project will focus on and what asset classes

### ISSUE THREAD

**Issue by raulfrk** [Vis4Sense/student-projects#7]
As described in the project proposal the main market will be the US equity market (stocks) and cryptocurrency. For this purpose the ideal platform to use for trading is Alpaca.markets.

Investigate if there are any further components to analyse for the purpose of the project. Consider futures and options as possible trading asset classes (derivatives) and whether they should be included.

**Comment by kaidatavis** [comment]
It is important to keep a record of all the resources we considered, including those we decided as not suitable (including why), so others can better follow up the work later if needed.

**Comment by raulfrk** [comment]
I have written a document in my folder with a brief description of the asset classes I will be using for my project, why I chose those and what platform I will be using for API trading and why. I have created a PR for that.
