### ISSUE TITLE
Decide on a research direction and come up with high level plan

### ISSUE THREAD

**Issue by rachanahegde** [Vis4Sense/student-projects#75]
[Here](https://github.com/Vis4Sense/student-projects/blob/main/2023-2024/rachana-hegde/updated_project_plan.md) is my updated project plan.

**Comment by kaidatavis** [comment]
I suggest we continue the discussion in this issue. 

You can put your updated proposal as a markdown file in your repository folder and link to it here.

The new plan looks good. Maybe the research contribution can come from supporting writers to fine tune the model themselves, assuming they have limited knowledge on generative AI.

If we want to make this into a paper, it will be good to find a paper as an example/template in terms of the research contribution, evaluation, paper organisation, etc.
